### ISSUE TITLE
[INCOMPATIBILITY] Concurrent Chunk Management Engine (C2ME)

### ISSUE THREAD

**Issue by iSimilaXi** [squeeglii/grapplemod#4]
**Describe the bug**
The game kicked out to main menu after right-click to use grappling hook while using C2ME
removing C2ME solves the problem.

**Video / Screenshots**
https://imgur.com/a/qU2QZy5

**Version**
Include the versions for:
 - The Grapple Hook Mod v1.1 
 - Fabric 0.14.13
 - Minecraft 1.19.2
 - C2ME 0.2.0+alpha.9.0

**Output Log**
<detail>
[17:36:36] [Netty Acceptor IO Thread/ERROR]: Encountered exception while handling in channel with name "grapplemod:keypress"
java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Thread[#174,Server thread,8,main], current: Thread[#196,Netty Acceptor IO Thread,5,main])
	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:32) ~[c2me-fixes-worldgen-threading-is0+alpha.9.0-c1c04bad330d4dfb.jar:?]
	at net.minecraft.class_6566.method_43057(class_6566.java:56) ~[client-intermediary.jar:?]
	at com.yyon.grapplinghook.item.GrapplehookItem.throwBoth(GrapplehookItem.java:229) ~[grapplemod-1.19.2-v1.1.jar:?]
	at com.yyon.grapplinghook.item.GrapplehookItem.onCustomKeyDown(GrapplehookItem.java:137) ~[grapplemod-1.19.2-v1.1.jar:?]
	at com.yyon.grapplinghook.network.serverbound.KeypressMessage.processMessage(KeypressMessage.java:70) ~[grapplemod-1.19.2-v1.1.jar:?]
	at com.yyon.grapplinghook.network.NetworkManager.lambda$generateServerPacketHandler$1(NetworkManager.java:39) ~[grapplemod-1.19.2-v1.1.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) [fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.minecraft.class_3244.handler$djd000$handleCustomPayloadReceivedAsync(class_3244.java:2061) [client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) [client-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) [client-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) [client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
[17:36:36] [Worker-Main-1/INFO]: [STDOUT]: Stronghold positions initialized
[17:36:36] [Netty Local Client IO #0/INFO]: Disconnected from server, resetting proxy config values
[17:36:36] [Server thread/INFO]: iSimilaXi lost connection: Internal Exception: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Thread[#174,Server thread,8,main], current: Thread[#196,Netty Acceptor IO Thread,5,main])
</detail>

**Steps To Reproduce**
While using C2ME mod, hold grappling hook in main hand and right-click to use grappling hook.

**Comment by squeeglii** [comment]
Patched in commit [79b1933](https://github.com/CloudG360/grapplemod-restitched/commit/79b1933fa1c5c9591d33961b2cfb39ab6feb7074) - should be released in v1.2 in a few days. :)
